aws_count=1
aws_az="ap-south-1"
instance_port={"HTTP": 80}
lb_port={"HTTP": 80}
instance_protocol=["HTTP"]
lb_protocol={"HTTP" : "HTTP"}
aws_ami="ami-0af25d0df86db00c1"
health_check_target="HTTP:80/index.php"
internal=false
health_check_interval=10
health_check_timeout=2
associate_public_ip=true
sg_id=[""]
instance_type="t2.micro"
